// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/wwwroot/LLMRAGTools/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import ApiOutlined from 'D:/wwwroot/LLMRAGTools/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import BookOutlined from 'D:/wwwroot/LLMRAGTools/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BookOutlined';
import MailOutlined from 'D:/wwwroot/LLMRAGTools/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MailOutlined';
import SettingOutlined from 'D:/wwwroot/LLMRAGTools/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { HomeOutlined, ApiOutlined, BookOutlined, MailOutlined, SettingOutlined };
